language: node_js

node_js:
  - "node"
  - "10"
  - "8"

before_script:
  - npm run install

script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - npm run typedoc

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
    - apisupport@zenvia.com
